name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 22.21.0
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test
